import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Knowlace!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

            <div className="flex flex-col min-h-screen">

              <header className="w-full border-b border-white/10 bg-[#1e3a7f]">
                <div className="max-w-6l mx-auto px-6 py-4 flex justify-between items-center">
                  <h1 className="text-xl font-bold text-white">
                    Knowlace.
                  </h1>

                  <nav className="space-x-6 text-sm text-white">
                    <a href="#">About</a>
                    <a href="#">Login</a>
                  </nav>
                </div>
              </header>

              <main className="flex-1">
                {children}
              </main>

            </div>
          
      </body>
    </html>
  );
}
